In [4]:
import pandas as pd
df_master=pd.read_excel('C:/Users/polif/Documents/MYpython/商品情報マスタ.xlsx')
df_master

      商品コード     品名  単価[¥/L] or [¥]
0   GSL0001  レギュラー             120
1   GSL0002   ハイオク             160
2   GSL0003     軽油             100
3   GSL0004     灯油              80
4   CMT0001   洗車 A             500
5   CMT0002   洗車 B            1500
6   CMT0003   洗車 C            3000
7   CMT0004  オイル交換            1000
8   CMT0005  タイヤ交換            4000
9   GDS0001    タイヤ            8000
10  GDS0002    コロン             800
11  GDS0003   スナック             100

In [6]:
df_order=pd.read_excel('C:/Users/polif/Documents/MYpython/注文表.xlsx')
df_order

           日付    商品コード  数量
0  2020-12-01  GSL0001  40
1  2020-12-02  GSL0002  50
2  2020-12-03  GSL0001  35
3  2020-12-15  GSL0004  60
4  2020-12-15  CMT0003   2
5  2020-12-18  GSL0004  15
6  2020-12-21  CMT0003   4
7  2020-12-22  GSL0004  22
8  2020-12-22  CMT0005   3
9  2020-12-25  GSL0004  32
10 2020-12-28  CMT0004   4

In [7]:
#vlookupはmergeを使用する
pd.merge(df_order,df_master,how='inner')

           日付    商品コード  数量     品名  単価[¥/L] or [¥]
0  2020-12-01  GSL0001  40  レギュラー             120
1  2020-12-03  GSL0001  35  レギュラー             120
2  2020-12-02  GSL0002  50   ハイオク             160
3  2020-12-15  GSL0004  60     灯油              80
4  2020-12-18  GSL0004  15     灯油              80
5  2020-12-22  GSL0004  22     灯油              80
6  2020-12-25  GSL0004  32     灯油              80
7  2020-12-15  CMT0003   2   洗車 C            3000
8  2020-12-21  CMT0003   4   洗車 C            3000
9  2020-12-22  CMT0005   3  タイヤ交換            4000
10 2020-12-28  CMT0004   4  オイル交換            1000

In [8]:
df_merged=pd.merge(df_order,df_master,how='inner')
df_merged.head()

          日付    商品コード  数量     品名  単価[¥/L] or [¥]
0 2020-12-01  GSL0001  40  レギュラー             120
1 2020-12-03  GSL0001  35  レギュラー             120
2 2020-12-02  GSL0002  50   ハイオク             160
3 2020-12-15  GSL0004  60     灯油              80
4 2020-12-18  GSL0004  15     灯油              80

In [9]:
df_merged['数量'] * df_merged['単価[¥/L] or [¥]']

0      4800
1      4200
2      8000
3      4800
4      1200
5      1760
6      2560
7      6000
8     12000
9     12000
10     4000
dtype: int64

In [11]:
df_merged['金額']=df_merged['数量'] * df_merged['単価[¥/L] or [¥]']
df_merged

           日付    商品コード  数量     品名  単価[¥/L] or [¥]     金額
0  2020-12-01  GSL0001  40  レギュラー             120   4800
1  2020-12-03  GSL0001  35  レギュラー             120   4200
2  2020-12-02  GSL0002  50   ハイオク             160   8000
3  2020-12-15  GSL0004  60     灯油              80   4800
4  2020-12-18  GSL0004  15     灯油              80   1200
5  2020-12-22  GSL0004  22     灯油              80   1760
6  2020-12-25  GSL0004  32     灯油              80   2560
7  2020-12-15  CMT0003   2   洗車 C            3000   6000
8  2020-12-21  CMT0003   4   洗車 C            3000  12000
9  2020-12-22  CMT0005   3  タイヤ交換            4000  12000
10 2020-12-28  CMT0004   4  オイル交換            1000   4000